apiVersion: apps/v1
kind: Deployment
metadata:
  name: rethinkdb-{{ .Release.Name }}
  labels:
    app: rethinkdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  template:
    metadata:
    {{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: rethinkdb
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      containers:
      - name: defiant
        image: "rethinkdb:2.3.6"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - containerPort: 28015
            protocol: TCP
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
          - mountPath: /data
            name: rethinkdb-data
      volumes:
        - name: rethinkdb-data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (printf "%s-%s" (.Release.Name) "data") | quote  }}
        {{- else }}
          emptyDir: {}
        {{- end }}
