apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptrace.fullname" . }}
  labels:
    app: uptrace
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: uptrace
    {{- include "uptrace.selectorLabels" . | nindent 4 }}
