apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptrace.fullname" . }}
  labels:
    {{- include "uptrace.labels" . | nindent 4 }}
data:
  uptrace.yml: |
{{ .Values.uptrace.config | toYaml | indent 4 }}
