apiVersion: v1
kind: Service
metadata:
  name: {{ include "website.fullname" . }}
  labels:
{{ include "website.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "website.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
