image:
  tag: latest
  pullPolicy: Always

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 50m
  hosts:
    - host: twitton.poire.dev
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: poire.dev-wildcard-tls
      hosts:
        - twitton.poire.dev

twitton:
  webDomain: twitton.poire.dev
  localDomain: twitton.poire.dev
  adminUsername: aram
  adminKeySecretName: twitton-admin-keys
  adminIconUrl: https://i.imgur.com/DyflGFV.png
