image:
  name: registry.gitlab.com/momothereal/momoperes.ca/defiant
  tag: latest
  pullPolicy: Always

podAnnotations: {}

nodeSelector: {}
tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  annotations:
    "helm.sh/resource-policy": keep
  storageClass: do-block-storage
  storageSize: 1Gi
