image:
  repository: teamspeak
  tag: latest
  pullPolicy: Always

podAnnotations: {}

service:
  type: NodePort
  voicePort: 30987
  filePort: 30033

nodeSelector:
  teamspeak: "1"

tolerations: []
affinity: {}

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  annotations:
    "helm.sh/resource-policy": keep
  storageClass: do-block-storage
  storageSize: 1Gi
  existingClaim: teamspeak-data
