apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: public-ingress
  namespace: public
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  tls:
    - hosts:
        - momoperes.ca
      secretName: momoperes.ca-wildcard-tls
  rules:
    - host: momoperes.ca
      http:
        paths:
          - path: /
            backend:
              serviceName: website
              servicePort: 9000
