env:
  open:
    AUTH_ANONYMOUS_GET: true
    DISABLE_API: false
  existingSecret: chartmuseum-credentials
  existingSecretMappings:
    BASIC_AUTH_USER: username
    BASIC_AUTH_PASS: password

service:
  servicename: chartmuseum

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 80m
    memory: 64Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: do-block-storage
